ADS500B Final Team Project
Lindy Conrad, Jordan Torres, & Alli McKernan
Dataset 2 (House Sales)

1) Data Importing & Pre-processing

In [8]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Import dataset
file_path = '/Users/allig/ads500b/house_sales.csv'  # file path
data = pd.read_csv(file_path)

# Describe dataset characteristics
print("Dataset Dimensions:", data.shape)
print("\nData Types:\n", data.dtypes)
print("\nFirst few rows of the dataset:\n", data.head())
print("\nDataset Description:\n", data.describe())

# Clean and wrangle data
# Fill missing values with the median for continuous variables
data['bedrooms'] = data['bedrooms'].fillna(data['bedrooms'].median())
data['bathrooms'] = data['bathrooms'].fillna(data['bathrooms'].median())
data['sqft_living'] = data['sqft_living'].fillna(data['sqft_living'].median())
data['sqft_lot'] = data['sqft_lot'].fillna(data['sqft_lot'].median())

# Transform data
# Convert `date` to datetime format
data['date'] = pd.to_datetime(data['date'], format='%Y%m%dT%H%M%S')

# Normalize continuous variables and create new columns for normalized values
scaler = MinMaxScaler()
data[['norm_price', 'norm_sqft_living', 'norm_sqft_lot', 'norm_sqft_above', 'norm_sqft_basement', 
      'norm_lat', 'norm_long', 'norm_sqft_living15', 'norm_sqft_lot15']] = scaler.fit_transform(
    data[['price', 'sqft_living', 'sqft_lot', 'sqft_above', 'sqft_basement', 'lat', 'long', 
          'sqft_living15', 'sqft_lot15']]
)

# Feature construction based on existing ones- 'age' & 'years_since_renovation'
data['age'] = 2024 - data['yr_built']
data['years_since_renovation'] = data['yr_renovated'].apply(lambda x: 2024 - x if x > 0 else 0)

# Reduce redundant data
# Drop redundant columns
data = data.drop(columns=['id', 'yr_built', 'yr_renovated'])

# Discretization: Create bins for sqft_living
data['sqft_living_bins'] = pd.cut(data['sqft_living'], bins=5, labels=False)

# Display cleaned and transformed data
print("\nCleaned and Transformed Data (first few rows):\n", data.head())

# Save the cleaned and transformed data to a new CSV file
output_file_path = '/Users/allig/ads500b/cleaned_house_sales.csv'
data.to_csv(output_file_path, index=False)
print(f"Cleaned and transformed dataset has been saved to {output_file_path}")

Dataset Dimensions: (21613, 21)

Data Types:
 id                 int64
date              object
price            float64
bedrooms         float64
bathrooms        float64
sqft_living      float64
sqft_lot         float64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
dtype: object

First few rows of the dataset:
            id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0       3.0       1.00       1180.0
1  6414100192  20141209T000000  538000.0       3.0       2.25       2570.0
2  5631500400  20150225T000000  180000.0       2.0       1.00        770.0
3  2487200875  20141209T000000  604000.0       4.0       3.00       1960.0
4  1954400510  20150218T000000  510000.0       3.0       2.00       1680.0

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0    5650.0     1.0           0     0  ...      7        1180              0
1    7242.0     2.0           0     0  ...      7        2170            400
2   10000.0     1.0           0     0  ...      6         770              0
3    5000.0     1.0           0     0  ...      7        1050            910
4    8080.0     1.0           0     0  ...      8        1680              0

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340
1      1951          1991    98125  47.7210 -122.319           1690
2      1933             0    98028  47.7379 -122.233           2720
3      1965             0    98136  47.5208 -122.393           1360
4      1987             0    98074  47.6168 -122.045           1800

   sqft_lot15
0        5650
1        7639
2        8062
3        5000
4        7503

[5 rows x 21 columns]

Dataset Description:
                  id         price      bedrooms     bathrooms   sqft_living  \
count  2.161300e+04  2.161300e+04  20479.000000  20545.000000  20503.000000
mean   4.580302e+09  5.400881e+05      3.372821      2.113507   2081.073697
std    2.876566e+09  3.671272e+05      0.930711      0.768913    915.043176
min    1.000102e+06  7.500000e+04      0.000000      0.000000    290.000000
25%    2.123049e+09  3.219500e+05      3.000000      1.500000   1430.000000
50%    3.904930e+09  4.500000e+05      3.000000      2.250000   1920.000000
75%    7.308900e+09  6.450000e+05      4.000000      2.500000   2550.000000
max    9.900000e+09  7.700000e+06     33.000000      8.000000  12050.000000

           sqft_lot        floors    waterfront          view     condition  \
count  2.056900e+04  21613.000000  21613.000000  21613.000000  21613.000000
mean   1.517982e+04      1.494309      0.007542      0.234303      3.409430
std    4.148617e+04      0.539989      0.086517      0.766318      0.650743
min    5.200000e+02      1.000000      0.000000      0.000000      1.000000
25%    5.040000e+03      1.000000      0.000000      0.000000      3.000000
50%    7.620000e+03      1.500000      0.000000      0.000000      3.000000
75%    1.070800e+04      2.000000      0.000000      0.000000      4.000000
max    1.651359e+06      3.500000      1.000000      4.000000      5.000000

              grade    sqft_above  sqft_basement      yr_built  yr_renovated  \
count  21613.000000  21613.000000   21613.000000  21613.000000  21613.000000
mean       7.656873   1788.390691     291.509045   1971.005136     84.402258
std        1.175459    828.090978     442.575043     29.373411    401.679240
min        1.000000    290.000000       0.000000   1900.000000      0.000000
25%        7.000000   1190.000000       0.000000   1951.000000      0.000000
50%        7.000000   1560.000000       0.000000   1975.000000      0.000000
75%        8.000000   2210.000000     560.000000   1997.000000      0.000000
max       13.000000   9410.000000    4820.000000   2015.000000   2015.000000

            zipcode           lat          long  sqft_living15     sqft_lot15
count  21613.000000  21613.000000  21613.000000   21613.000000   21613.000000
mean   98077.939805     47.560053   -122.213896    1986.552492   12768.455652
std       53.505026      0.138564      0.140828     685.391304   27304.179631
min    98001.000000     47.155900   -122.519000     399.000000     651.000000
25%    98033.000000     47.471000   -122.328000    1490.000000    5100.000000
50%    98065.000000     47.571800   -122.230000    1840.000000    7620.000000
75%    98118.000000     47.678000   -122.125000    2360.000000   10083.000000
max    98199.000000     47.777600   -121.315000    6210.000000  871200.000000

Cleaned and Transformed Data (first few rows):
         date     price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0 2014-10-13  221900.0       3.0       1.00       1180.0    5650.0     1.0
1 2014-12-09  538000.0       3.0       2.25       2570.0    7242.0     2.0
2 2015-02-25  180000.0       2.0       1.00        770.0   10000.0     1.0
3 2014-12-09  604000.0       4.0       3.00       1960.0    5000.0     1.0
4 2015-02-18  510000.0       3.0       2.00       1680.0    8080.0     1.0

   waterfront  view  condition  ...  norm_sqft_lot  norm_sqft_above  \
0           0     0          3  ...       0.003108         0.097588
1           0     0          3  ...       0.004072         0.206140
2           0     0          3  ...       0.005743         0.052632
3           0     0          5  ...       0.002714         0.083333
4           0     0          3  ...       0.004579         0.152412

   norm_sqft_basement  norm_lat  norm_long  norm_sqft_living15  \
0            0.000000  0.571498   0.217608            0.161934
1            0.082988  0.908959   0.166113            0.222165
2            0.000000  0.936143   0.237542            0.399415
3            0.188797  0.586939   0.104651            0.165376
4            0.000000  0.741354   0.393688            0.241094

   norm_sqft_lot15  age  years_since_renovation  sqft_living_bins
0         0.005742   69                       0                 0
1         0.008027   73                      33                 0
2         0.008513   91                       0                 0
3         0.004996   59                       0                 0
4         0.007871   37                       0                 0

[5 rows x 30 columns]
Cleaned and transformed dataset has been saved to /Users/allig/ads500b/cleaned_house_sales.csv

2) Data Analysis & Visualization